name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install mypy
    - name: mypy
      run: mypy --show-column-numbers --hide-error-context .
    - name: Unit Tests
      run: python3 -m unittest

  build_wheel:
    name: Build wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install build module
        run: pip install build

      - name: Build wheel and source
        run: python -m build --sdist --wheel --outdir dist/ .

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload_pypi:
    needs: [build_wheel]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.8.3
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
